version: 0.2
phases:
 install:
  runtime-versions:
   nodejs: 14
 build: 
  commands:
   - export BUCKET=test-pipeline-output-code
   - aws cloudformation package --s3-bucket $BUCKET --s3-prefix codepipeline --output-template-file outputtemplate.yml
artifacts:
 type: zip
 files:
  - template.yml
  - outputtemplate.yml
