version: 0.2
phases:
 install:
  runtime-versions:
   nodejs: 14
 build: 
  commands:
   - echo "Start building..."
   - export BUCKET=test-pipeline-output-code
   - export SAM_CLI_TELEMETRY=0
   - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yml
   - cat outputtemplate.yml
   - # aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --s3-prefix codepipeline --output-template-file outputtemplate.yml
artifacts:
 type: zip
 files:
  - template.yml
  - outputtemplate.yml
